function add(a, b) {
  return a + b;
}

function throwException() {
  throw 'SampleException';
}